version: '3.9'

services:
  app:
    container_name: neuro-blogger-telegram-bot
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - LOG_DIR=/tmp/logs
      - SECRET_KEY=secretKey
      - CREDENTIALS=true
      - ORIGIN=*
      - LOG_FORMAT=combined
    user: 'node'
    restart: 'unless-stopped'

  proxy:
    container_name: proxy
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    restart: 'unless-stopped'
